### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by akaszynski** [joergbuchwald/ogs6py#14]
Hello,

I'm reviewing your [submission](https://github.com/joergbuchwald/joss_ogs6py_VTUinterface) for JOSS and having a tough time getting started installing your library.  I'd suggest the following:
- Provide a package of your library on PyPi
- Check for an installation of OGS and then raise a descriptive error when the application is missing.  For example, immediately after:
  https://github.com/joergbuchwald/ogs6py/blob/354945b8499fa30829013648f03946d5d9e89bc1/ogs6py/ogs.py#L114-L117
 Add a test if the file exists with `os.path.isfile`, and then point the user to a url containing application installation directions.
- Avoid non-descriptive runtime errors:
 https://github.com/joergbuchwald/ogs6py/blob/354945b8499fa30829013648f03946d5d9e89bc1/ogs6py/ogs.py#L139

Cheers!
Alex

**Comment by leouieda** [comment]
Related to openjournals/joss-reviews#3673 (so we can see the status in the review issue)

**Comment by joergbuchwald** [comment]
Hi @akaszynski,
thanks for reviewing. Concerning the first point, ogs6py is already on PyPI: https://pypi.org/project/ogs6py/
Perhaps, I should add that to the installation instructions as well...

**Comment by akaszynski** [comment]
> thanks for reviewing. Concerning the first point, ogs6py is already on PyPI: https://pypi.org/project/ogs6py/
Perhaps, I should add that to the installation instructions as well...

Ha!  I feel stupid for not even looking.  Yes, directions would be helpful for that.
