### ISSUE TITLE
Suggestions from JOSS review

### ISSUE THREAD

**Issue by cpgr** [joergbuchwald/ogs6py#17]
Overall I think this is a pretty good tool for the OGS community, so well done.

I have some minor suggestions:
- You should document how to run the tests in the README, preferably just after the installation instructions. It is always good to know that something has installed and is working as intended. I originally ran `tests\test_ogs6py.py` from within the `tests` directory and got a load of missing file errors. It obviously has to be run from the main `os6py` directory (all the tests passed when I ran it there 😄).
- You might want to mention somewhere that this requires python >= 3.8 (pretty sure that assignment expressions `:=` don't work in versions < 3.8).

Refs  openjournals/joss-reviews#3673

**Comment by leouieda** [comment]
> somewhere that this requires python >= 3.8

Ideally you can also set the `python_requires` argument in `setup.py` but it's always good to state in the docs somewhere as well.

**Comment by joergbuchwald** [comment]
Thanks for the suggestions, I added a note to the readme concerning the python version as well as how to run the unittests and also enforced the python version 3.8 in `setup.py`.
