### ISSUE TITLE
Feature request: Run ogs with some wrapper (e.g. mpirun)

### ISSUE THREAD

**Issue by bilke** [joergbuchwald/ogs6py#25]
It would be nice if there were arguments to `run_model()` which specify a wrapper and its arguments, e.g. for running with MPI. Example API:

```python
model.run_model(logfile="out.log", wrapper="mpirun", wrapper_args="-np 3")
```

This would call `mpirun -np 3 ogs path/to/project.prj > out.log` behind the scenes.

**Comment by joergbuchwald** [comment]
I think it simplifies things to have only wrapper as a function argument or is there a good reason you would distinguish between the wrapper and its arguments?

**Comment by bilke** [comment]
Thanks a lot!
