### ISSUE TITLE
Optional writing of log file

### ISSUE THREAD

**Issue by garibay-j** [joergbuchwald/ogs6py#27]
First, thanks Joerg for this awesome tool! I was wondering if it would be possible to make optional the writing of the log file when using the `model.run_model()` method. This is because, for some long running models (with many time steps) the log file quickly becomes huge in size, and for some users this output may not be needed.

**Comment by joergbuchwald** [comment]
Good point. It makes it hard to track errors, but maybe a good error message could help then.

**Comment by garibay-j** [comment]
Yes, I agree. Thank you for adding the switch so quickly!
