### ISSUE TITLE
details on example_replace

### ISSUE THREAD

**Issue by dominik-kern** [joergbuchwald/ogs6py#3]
**Great tool!**
It would be nice, if in the preamble of ``example_replace.py`` would be mentioned that it refers to ``test.prj`` generated by ``example_THM.py``.
And in this example _porosity_ is not a medium but a phase property.

**Comment by joergbuchwald** [comment]
Thanks for reporting. I added a comment.
The annoying thing is that the porosity (and some other properties) should be a medium property for months now, but the merge request is still pending....
