### ISSUE TITLE
"value" in "model.media.add_property"

### ISSUE THREAD

**Issue by muellerchr** [joergbuchwald/ogs6py#41]
I have some problems using the method "model.media.add_property" and the method parameter "value", e.g. model.media.add_property(medium_id="0", name="porosity", type="constant", value="42"). It seems that the OGS tag "value" is not written to the OGS project file? What am I doing wrong?

Thanks for the effort to develop such a great tool!
Christian

**Comment by joergbuchwald** [comment]
Hi!
there is a case-sensitive type check. I think this is most likely related to the small case "c". Using `Constant` instead should work. This example is also part of [example_THM.py](https://github.com/joergbuchwald/ogs6py/blob/master/examples/example_THM.py#L59).

**Comment by muellerchr** [comment]
Worked! Thanks for the quick reply!
