### ISSUE TITLE
lxml error when reading large files

### ISSUE THREAD

**Issue by psatke** [joergbuchwald/ogs6py#74]
This file [ogs_3bhe_gw.zip](https://github.com/joergbuchwald/ogs6py/files/14258817/ogs_3bhe_gw.zip) produces the following error: 

**XMLSyntaxError: xmlSAX2Characters: huge text node, line 762, column 10003741**

when the piece of code is executed (ogs6py version 0.370):
```python
from ogs6py import ogs

file = 'ogs_3bhe_gw.prj'

model = ogs.OGS(PROJECT_FILE=file, INPUT_FILE=file)
```

I tried to reduce the project file to a minimum example, but smaller files did not reproduce the error.
My current workaround looks like this:
```python
from lxml import etree

file = 'ogs_3bhe_gw.prj'

parser = etree.XMLParser(huge_tree=True)
tree = etree.parse(file, parser)
root = tree.getroot()
```

Please consider to add the possibility to set ```huge_tree=True``` via the API.

**Comment by joergbuchwald** [comment]
Thanks for the hint. I'll take a look.
