### ISSUE TITLE
multiple concentration process variables for component transport models not working

### ISSUE THREAD

**Issue by HeiJuli** [joergbuchwald/ogs6py#77]
At the moment only one concentration process variable can be set. It would be useful to have the opportunity to allow multiple concentration process variables in order to allow simulations of multiple components. It refers to this function: `ogs6py.classes.processes.add_process_variable()`

**Comment by joergbuchwald** [comment]
Could you please check if the problem persists?
Keep in mind that the Syntax slightly changed. The old method is now split-up into two methods:
```Python
add_process_variable(process_variable, process_variable_name)
add_secondary_variable(internal_name, output_name)
```

**Comment by HeiJuli** [comment]
looks good, thanks for fixing it.
