### ISSUE TITLE
In time_loop.add_output() repeat needs to be defined, which is incorrect. 

### ISSUE THREAD

**Issue by HeiJuli** [joergbuchwald/ogs6py#81]
If you want to define the output in time loop it is sufficient to define fixed output times. But ogs6py throws error if repeat is not defined. The prj-file works without repeat being defined. For example, a correct output looks like. 

```
<output>
            <type>VTK</type>
            <prefix>line</prefix>
            <fixed_output_times>2419200 4838400 7257600 9676800 14515200 31449600 48384000</fixed_output_times>
            <variables>
                <variable>Ba-133</variable>
                <variable>pressure</variable>
            </variables>
</output>
```

**Comment by HeiJuli** [comment]
the corresponding ogs6py function could be: 

model.timeloop.add_output(
        type="VTK",
        prefix=str("test"),
        variables=["test1","test2"],
        fixed_output_times=[
            2419200,
            4838400,
            7257600,
            9676800,
            14515200,
            31449600,
            48384000,
        ],
    )

**Comment by joergbuchwald** [comment]
Could you check whether the problem persists?

**Comment by HeiJuli** [comment]
its fixed

**Comment by HeiJuli** [comment]
sorry I closed the issue too early
There is an remnant left: 
`<timesteps/>`still is printed to the prj-file, therefore ogs complains about: `error: You have not given any pair (<repeat/>, <each_steps/>) that defines at which timesteps output shall be written. Aborting.`
